// <auto-generated />
namespace HostelSystem_TestWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Fixing_Keys : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Fixing_Keys));
        
        string IMigrationMetadata.Id
        {
            get { return "202108081602428_Fixing_Keys"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
