// <auto-generated />
namespace HostelSystem_TestWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Extending_Guest_model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Extending_Guest_model));
        
        string IMigrationMetadata.Id
        {
            get { return "202108081721016_Extending_Guest_model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
